name: GitHub Action Validator
description: A GitHub action to validate your GitHub (action) workflows
author: jazzsequence
branding:
  icon: refresh-cw
  color: orange
inputs:
  path-to-workflows:
    description: The path to where your GitHub action workflow files are located. Defaults to `.github/workflows/*.yml`.
    required: false
    default: '.github/workflows/*.yml'
  show-ascii-art:
    description: Shows a silly Xzibit "Yo Dawg" ascii art before running the validator. Defaults to true.
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install prebuilt rust-script
      shell: bash
      run: |
        if ! command -v rust-script &> /dev/null; then
          echo "⚙️ Downloading prebuilt rust-script..."
          curl -sSL -o rust-script.tar.gz https://github.com/fornwall/rust-script/releases/latest/download/rust-script-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf rust-script.tar.gz
          chmod +x rust-script
          sudo mv rust-script /usr/local/bin/rust-script
        fi
    - name: Install action-validator
      shell: bash
      run: |
        # Fetch the latest release version dynamically from GitHub API
        VERSION=$(curl -sSL https://api.github.com/repos/mpalmer/action-validator/releases/latest | jq -r '.tag_name')
        FILE_NAME="action-validator_linux_amd64"
        DOWNLOAD_URL="https://github.com/mpalmer/action-validator/releases/download/${VERSION}/${FILE_NAME}"
        echo "Downloading mpalmer/action-validator ${VERSION} from ${DOWNLOAD_URL} ..."
        curl -sSL -o action-validator "$DOWNLOAD_URL"

        # Validate that the file is a valid binary
        if ! file action-validator | grep -q "ELF"; then
          echo "Download failed or invalid binary. Exiting."
          exit 1
        fi

        # Make executable and move to /usr/local/bin
        chmod +x action-validator
        sudo mv action-validator /usr/local/bin/action-validator
        action-validator -V
    - name: Show Ascii art
      shell: bash
      if: ${{ inputs.show-ascii-art == 'true' }}
      run: |
        bash ${{ github.action_path }}/bin/do-ascii.sh
    - name: Validate Workflows
      shell: bash
      run: bash ${{ github.action_path }}/bin/validate.sh "${{ inputs.path-to-workflows }}"
